name: Exportar Modelo para TFLite no Linux

on:
  workflow_dispatch: # Ativa o botão manual no site do GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install ultralytics

      - name: Executar Exportação Oficial na Pasta Correta
        run: |
          cd projetos/3-deteccao-mascaras
          python optimize_model.py

      - name: Disponibilizar o modelo para Download (Artefato)
        uses: actions/upload-artifact@v4
        with:
          name: modelo-tflite-convertido
          path: projetos/3-deteccao-mascaras/model.tflite
          if-no-files-found: error