name: Exportar Modelo para TFLite no Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências Estáveis
        run: |
          pip install ultralytics onnx
          pip install tensorflow-cpu==2.15.0  # Versão ultra estável sem bugs de compilação
          pip install git+https://github.com/onnx/onnx-tensorflow.git

      - name: Executar Exportação e Conversão Direta
        run: |
          cd projetos/3-deteccao-mascaras
          # Executa o script para gerar o model.onnx
          python optimize_model.py
          
          # Executa o comando direto do terminal para converter o ONNX para TFLite pulando o erro do litert
          onnx-tf convert -i model.onnx -o model_pb
          python -c "import tensorflow as tf; converter = tf.lite.TFLiteConverter.from_saved_model('model_pb'); tflite_model = converter.convert(); open('model.tflite', 'wb').write(tflite_model)"
          echo "Conversão concluída com sucesso!"

      - name: Disponibilizar o modelo para Download
        uses: actions/upload-artifact@v4
        with:
          name: modelo-tflite-convertido
          path: projetos/3-deteccao-mascaras/model.tflite
          if-no-files-found: error