name: Exportar Modelo para TFLite no Linux

on:
  workflow_dispatch: # Ativa o botão manual no site do GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para o robô fazer o commit de volta pro seu Git

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          pip install ultralytics

      - name: Executar Exportação Oficial na Pasta Correta
        run: |
          # Navega até a pasta onde o modelo e o script estão
          cd projetos/3-deteccao-mascaras
          python optimize_model.py

      - name: Forçar Auto-Commit do arquivo gerado para o repositório
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Adiciona o arquivo gerado dentro da pasta correta do projeto
          git add projetos/3-deteccao-mascaras/model.tflite
          
          # O [skip ci] evita que esse commit dispare a esteira antes da hora
          git commit -m "Bot: Injetando model.tflite gerado no Linux [skip ci]" || echo "Nenhuma alteração para commitar"
          git push